name = "dark-coding-challenges"
logLevel = "debug"              # "debug" | "warn" | "error"
smol = true
telemetry = true
type = "module"

[install]
exact = false

[paths]
"@/*" = "./src/*"

[run]
# bun = true

[test]
coverage = true
# preload = [ "test/setup.ts" ]
