import { writeFile, readFile, mkdir, readdir, access } from "fs/promises";
import { resolve } from "path";
import prompts, { type PromptObject } from "prompts";
import { camelCase, snakeCase, kebabCase } from "change-case";
import { fileURLToPath } from "node:url";

const baseDirectory = fileURLToPath(new URL("src", import.meta.url));

export const hex = (input: string) => {
    const clean = input.replace(/[^a-f0-9]/gi, "");
    const buff = [];
    for (let i = 0; i < clean.length; i += 2) {
        buff.push(Number(`0x$${clean.slice(i, i + 2)}`));
    }
    return buff
};
export const rgb = (...input: number[]) =>
    input
        .flat(Infinity)
        .reduce((a, c) => a + c.toString(16).padStart(2, "0"), "#");

export type PromptResponse = PromptObject<string> & {
    moduleName?: string;
    functionName?: string;
    directory: string;
    filename: string;
};
const logger = (err: unknown, context?: string, ...args: unknown[]) => {
    if (err) {
        console.log(`[${context}]`, err, ...args);
    }
}
const autogenerated = "// === AUTOGENERATED IMPORTS ===";
const delimiter = "// -------------------imports-------------------//";

const createDirectory = async ({ directory, functionName }: PromptResponse) =>
    await mkdir(new URL(`./src/${directory}/`, import.meta.url), {
        recursive: true,
    });
const saveFile = async (
    directory: string,
    filename: string,
    extension: string,
    contents: string,
) => {
    const superDirectory = () => {
        if (/py/i.test(extension) || /test_/i.test(extension)) return "";
        if (/test.ts/i.test(extension)) return "test";
        return "src/";
    };
    const url = new URL(
        `./${superDirectory()}/${directory}/${filename}.${extension}`,
        import.meta.url,
    );
    await writeFile(url, contents);
};

const organizeRustImports = async ({ directory, filename }: PromptResponse) => {
    const location = resolve(baseDirectory, directory);
    const moduleLocation = resolve(location, "mod.rs");
    console.log(`Module location: ${moduleLocation}`);

    try {
        await access(moduleLocation);
    } catch (error) {
        logger(
            error,
            "organizeRustImports",
            location,
            `mod.rs not found at ${moduleLocation}`,
        );
        return null;
    }

    try {
        const files = await readdir(location);
        console.log(`Count of files in directory: ${files.length}`);
        const mods = new Set<string>();

        const data = await readFile(moduleLocation, "utf-8");

        const contents = data.includes(delimiter)
        ? data.substring(data.indexOf(delimiter))
        : "";

        files.forEach((file: string) => {
            if (file.endsWith(".rs") && file !== "mod.rs") {
                mods.add(file.replace(/\.rs$/, "").trim());
            }
        });

        mods.delete("mod.rs");

        mods.delete("mod");

        const imports = [...mods].sort().map((file) => `pub mod ${file};`);

        await writeFile(moduleLocation, `${imports.join("\n")}\n${contents}`);
        console.log(`Updated imports in ${moduleLocation}`);

    } catch (error) {
        if (!(error instanceof Error)) return null;
        if (error.code === "ENOENT")
            return logger(
                error,
                "organizeRustImports",
                `Directory or file not found: ${location}`,
                location,
            );
        return logger(
            error,
            "organizeRustImports",
            `Unexpected error: ${error.message}`,
        );
    }
};
const createJavascript = async ({
    directory,
    functionName,
}: PromptResponse) => {
    const name = camelCase(functionName ?? "");
    const filename = kebabCase(functionName ?? "");
    try {
        const module = `export const ${name} = () => {}`;
        const contents = `import { describe, test, expect } from "bun:test";
import { ${name} } from "~/${directory}/${filename}";

describe("${name}", () => {
    test.each([])("", (inputs, output) => {
        const result = ${name}(inputs);
        expect(result).toStrictEqual(output);
    });
});`;

        await saveFile(directory, filename, "ts", module);
        await saveFile(directory, filename, "test.ts", contents);
    } catch (error) {
        logger(error, "createJavascript", name, filename);
    }
};
const createZig = async ({
    directory,
    functionName,
    moduleName,
}: PromptResponse) => {
    const name = camelCase(functionName ?? "");
    const filename = snakeCase(functionName ?? "");
    try {
        const contents = `const std = @import("std");\nconst expectEqual = std.testing.expectEqual;\n\npub fn ${name}(minuend: i32, subtrahend: i32) i32 {\n\treturn minuend - subtrahend;\n}\ntest "" {\n\tconst a: i32 = 3;\n\tconst b: i32 = 2;\n\tconst c: i32 = 945;\n\tconst d: i32 = 422;\n\tconst difference = ${name}(a, b);\n\tconst e = ${name}(c, d);\n\ttry expectEqual(difference, 1);\n\ttry expectEqual(e, 523);\n}`;

        await saveFile(directory, filename, "zig", contents);
    } catch (error) {
        logger(error, "createZig", name, filename);
    }
};
const createPython = async ({
    directory,
    functionName,
    moduleName,
}: {
    moduleName: string;
    functionName: string;
    directory: string;
}) => {
    const name = snakeCase(functionName);
    try {
        const module = `\ndef ${name}():\n\treturn None`;
        const contents = `\nimport pytest\nfrom ${directory}.${name} import ${name}\n@pytest.mark.parametrize("num,expected",[])\ndef test_${name}(num, expected):\n\tassert ${name}(num) == expected`;

        await saveFile(directory, name, "py", module);
        await saveFile(directory, `test_${name}`, "py", contents);
    } catch (error) {
        logger(error, "createPython", name);
    }
};
const createRust = async ({
    directory,
    functionName,
    moduleName,
}: PromptResponse) => {
    const name = snakeCase(functionName ?? "");
    try {
        const contents = `pub fn ${name}() -> bool {\n//\n\n}\n#[cfg(test)]\nmod tests {\nuse super::${name};\n#[test]\nfn test_${name}() {\nassert_eq!(${name}(parameters), returnvalue);\n}\n}`;
        await saveFile(directory, name, "rs", contents);
    } catch (error) {
        logger(error, "createRust", name);
    }
};

const onSubmit = (prompt, answer, answers): void => {};

const onCancel = (): void => {};

const questions: PromptObject[] = [
    // {type: "select",name: "mainMenu",message: "What action do you want to complete",choices: [{ value: "colorizer", title: "Convert Color", },{ value: "scaffold", title: "Scaffold challenge files.", },]},
    {
        type: "select",
        name: "directory",
        message: "What type of problem is this?",
        choices: [
            { value: "easy", title: "Easy" },
            { value: "medium", title: "Medium" },
            { value: "hard", title: "Hard" },
            { value: "advanced", title: "Advanced" },
        ],
    },

    {
        name: "moduleName",
        type: "text",
        message: "What is the filename",
    },
    {
        type: "text",
        name: "functionName",
        message: "name of function",
    },
];
type UserResponse = {
    username: string;
    age: number;
};
async function main() {
    const response = (await prompts(questions, {
        onSubmit,
        onCancel,
    })) as PromptObject;
    if (!response?.functionName || !response?.directory) return;
    createRust(response).then(() => {
        createJavascript(response);
        createPython(response);
        createZig(response);
        organizeRustImports(response);
    });
}

main();
// console.log(rgb("#8ce4c3"))
// console.log(rgb(255, 237, 245))
// console.log(hex("#FFEDF5"))
// console.log(hex("$ec008c01"))
// console.log(rgb(236, 0, 140, 1))
// console.log(rgb( 47, 47, 46))
// writeFile(`./easy/${functionName}.rs`, rustFunction(functionName), (err) =>err)
