/*
 * This source file was generated by the Gradle 'init' task
 */

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    println("Hello World!")
}
