/*
 * This source file was generated by the Gradle 'init' task
 */

public class MainApp {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // Example of running challenges from different levels
        System.out.println("Running...\n");

        System.out.println("Running...\n");
        System.out.println(new App().getGreeting());

        System.out.println("Running...\n");
    }
}
